export { default as TextArchivo } from './TextArchivo';
export { default as Button } from './Button';
export { default as ScreenContainer } from './ScreenContainer';
export { default as Svg } from './Svg';
export { default as Input } from './Input';
export { default as Switch } from './Switch';
export { default as Stepper } from './Stepper';
export { default as Wizard } from './Wizard';
export { default as Checkbox } from './Checkbox';
